#!/usr/bin/env python

import sys

class BinaryCode:

    def calcul(self,i, num, input, output):
        if num!=0 and num!=1:
            return 'NONE'
        output.append(num)
        if i==0:
            if len(input)==1:
                if input[i] > 1:
                    return 'NONE'
                else:
                    return input[i]
            return self.calcul(i+1,input[i]-output[i], input, output)
        elif i==len(input)-1:
            if output[i] + output[i-1]==input[i]:
                str_output = []
                for item in output:
                    str_output.append(str(item))
                return ''.join(str_output)
            else:
                return 'NONE'
        else:
            return self.calcul(i+1,input[i]-(output[i]+output[i-1]), input, output)

    def decode(self,in_str):
        print in_str
        input = []
        for i in range(len(in_str)):
            input.append(int(in_str[i:i+1]))
        print 'len: ',len(input)
        output = []
        result = []
        result.append(self.calcul(0,0,input,output))
        output = []
        result.append(self.calcul(0,1,input,output))
        print tuple(result)
        return tuple(result)
